# Generated by Django 4.2.5 on 2023-09-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('number', models.TextField(max_length=15)),
                ('address', models.TextField(max_length=200)),
                ('image', models.ImageField(default='def.png', upload_to='prof_image/')),
                ('blood_group', models.CharField(blank=True, max_length=3, null=True)),
                ('nationality', models.CharField(max_length=15)),
                ('gender', models.CharField(blank=True, max_length=9, null=True)),
                ('relegion', models.CharField(blank=True, max_length=7, null=True)),
                ('qualification', models.CharField(max_length=15)),
                ('date_of_birth', models.CharField(max_length=15)),
                ('father_name', models.CharField(max_length=15)),
                ('mother_name', models.CharField(max_length=15)),
            ],
        ),
    ]
